name: .NET

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    
    env: 
      PACKAGE_PATH: ./product-catalog/Products.Catalog.sln
      TESTS_PATH: ./product-catalog/Products.Catalog.Tests.Integration/Products.Catalog.Tests.Integration.csproj
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    - name: Build
      run: dotnet build ${{ env.PACKAGE_PATH }}
    - name: Run tests
      run: dotnet test ${{ env.TESTS_PATH }} --no-build --verbosity minimal

